TOPLEVEL = Fib
MODULE = fib_test
VERILOG_SOURCES = $(WORKDIR)/gen/Fib.v $(WORKDIR)/gen/DelayElementSim_2.v $(WORKDIR)/gen/DelayElementSim_1.v $(WORKDIR)/gen/DelayElementSim_15.v

include $(shell cocotb-config --makefiles)/Makefile.sim