TOPLEVEL = Fifo

MODULE = fifo_test

VERILOG_SOURCES = ../../../../../gen/Fifo.v ../../../../../gen/DelayElement_1.v ../../../../../gen/DelayElement_2.v ../../../../../gen/DelayElement_3.v ../../../../../gen/DelayElement_4.v

include $(shell cocotb-config --makefiles)/Makefile.sim


